### ISSUE TITLE
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet` in tokio task

### ISSUE THREAD

**Issue by yvf** [Nukesor/webhook-server#17]
Hi, I'm having trouble starting the server with the below error.

Any idea what I'm doing wrong ? A quick google around suggests the error isn't unique, so hopefully I'm not doing something dumb.

```
webhook@homebridge:~$ RUST_BACKTRACE=full /usr/local/bin/webhookserver --help
01:42:58 [INFO] Init settings file
01:42:58 [INFO] Parsing config files
01:42:58 [INFO] Checking path: "/etc/webhook_server.yml"
01:42:58 [INFO] Parsing config file at: "/etc/webhook_server.yml"
01:42:58 [INFO] Checking path: "/home/webhook/.config/webhook_server.yml"
01:42:58 [INFO] Checking path: "./webhook_server.yml"
01:42:58 [INFO] Starting task executor with 6 workers
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-1.15.0/src/task/local.rs:305:18
stack backtrace:
   0:   0x8366a8 - std::backtrace_rs::backtrace::libunwind::trace::h0745d0de039f938b
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:   0x8366a8 - std::backtrace_rs::backtrace::trace_unsynchronized::h2cfd45a18ae62171
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0x8366a8 - std::sys_common::backtrace::_print_fmt::hd7f63f00d111b20d
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:   0x8366a8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5658aa5c3899b169
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:   0x85a304 - core::fmt::write::ha4dc14d2f32a78b7
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:   0x82f1bc - std::io::Write::write_fmt::h10f6c1f17bec6e53
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:   0x8384e0 - std::sys_common::backtrace::_print::h166185d048d68931
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:   0x8384e0 - std::sys_common::backtrace::print::h7eb887f4692b0a62
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:   0x8384e0 - std::panicking::default_hook::{{closure}}::hf5649c0be8d9aaf3
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:   0x837f88 - std::panicking::default_hook::hbf89cfc7bdc61c78
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:   0x838bb8 - std::panicking::rust_panic_with_hook::hbab80136205d859f
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:   0x838694 - std::panicking::begin_panic_handler::{{closure}}::h6dede74717d77f64
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  12:   0x836c18 - std::sys_common::backtrace::__rust_end_short_backtrace::h9a6e091a4c79afed
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:   0x8385ec - rust_begin_unwind
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  14:   0x44ba98 - core::panicking::panic_fmt::h582a2858119f9119
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  15:   0x858660 - core::panicking::panic_display::h678caffc97cc7e9d
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:64:5
  16:   0x44b9a8 - core::option::expect_failed::h6c331ab79067f617
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:1638:5
  17:   0x4a3798 - tokio::macros::scoped_tls::ScopedKey<T>::with::h137e192ad4073a1a
  18:   0x4e60b8 - actix::actor::Actor::start::h9f678437c6ce4968
  19:   0x503c38 - webhookserver::main::h025c83e08c9edaea
  20:   0x48388c - std::sys_common::backtrace::__rust_begin_short_backtrace::h4290d1cfaf47a85c
  21:   0x460f74 - std::rt::lang_start::{{closure}}::h0339eaa4bc8a0e0e
  22:   0x83639c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha7d1645291d1d2aa
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:259:13
  23:   0x83639c - std::panicking::try::do_call::h0db96c92370d7f1b
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  24:   0x83639c - std::panicking::try::h98639f80644be285
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  25:   0x83639c - std::panic::catch_unwind::hafca2e2c7f936058
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  26:   0x83639c - std::rt::lang_start_internal::{{closure}}::hb0d43718a52a7d1f
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:48
  27:   0x83639c - std::panicking::try::do_call::h3feecb1186d9a708
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  28:   0x83639c - std::panicking::try::h340edc61022f9342
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  29:   0x83639c - std::panic::catch_unwind::h7cfee2b2f512a5b1
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  30:   0x83639c - std::rt::lang_start_internal::h1aa71f44318724d6
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:20
  31:   0x503dc8 - main
  32: 0x76ccabe0 - __libc_start_main
                       at ./csu/./csu/libc-start.c:308:16
01:42:58 [INFO] Queue management actor started up
```

**Comment by yvf** [comment]
In case it helps, here's my `Cargo.toml`

```
[package]
name = "webhook-server"
description = "A simple web server to easily execute scripts/executables on incoming requests."
version = "0.1.5"
authors = ["Arne Beer <contact@arne.beer>"]
repository = "https://github.com/nukesor/webhook-server"
homepage = "https://github.com/nukesor/webhook-server"
documentation = "https://docs.rs/webhook-server"
license = "MIT"
keywords = ["webhook", "server", "script", "executor", "https"]
readme = "README.md"
edition = "2018"

[[bin]]
name = "webhookserver"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html                                                                                                            

[dependencies]
anyhow = "1"
log = "0.4"
simplelog = "0.10"
config = "0.11"
dirs = "4"
chrono = { version="0.4", features=["serde"] }
futures = "0.3"

actix = "0.12"
actix-rt = "2"
actix-web = { version="4.0.0-beta.10", features=["rustls"] }
rustls = "0.20"
rustls-pemfile = "0.2"

serde = "1"
serde_yaml = "0.8"
serde_json = "1"
handlebars = "4"
subprocess = "^0.2"

hmac = "0.11"
sha-1 = "0.9"
base64 = "0.13"
hex = "0.4"
```

**Comment by Nukesor** [comment]
Could you share your system specs, OS, etc?
The name of the home directory and hostname let's me suspect that this is a raspberry pi?

**Comment by Nukesor** [comment]
Ah nevermind.

You're probably using `v1.0.5`?
That update is broken and should actually be yanked from crates.io. `v0.1.4` however should still work.

I tried to update to a new version of actix-web, but for some reason the server crashes. I hadn't time to investigate this, as this project has a pretty low priority on my current schedule :sweat:.

Any help with this would be very much appreciated!

**Comment by yvf** [comment]
Yes, it is a RPI 3b+

OK, checked out 0.1.4 and building that now. It'll be a little while... the CPU isn't exactly fast. I'll let you know if that works. I can try to have a look, but I'm a Rust newbie. Any pointers as to where I should start digging might give me a head start, if you have any suspicions as to what may be going wrong. Did some API change, or is one of the recent commits suspect maybe ?

**Comment by yvf** [comment]
v0.1.4 is giving me a `mismatched types` error:

```
HEAD is now at 5dbc459 (cargo-release) version 0.1.4
pi@homebridge:~/webhook-server $ cargo install --path .
  Installing webhook-server v0.1.4 (/home/pi/webhook-server)
    Updating crates.io index
  Downloaded base64 v0.11.0
  Downloaded dirs v2.0.2
  Downloaded rustls v0.17.0
  Downloaded subtle v1.0.0
  Downloaded hmac v0.7.1
  Downloaded crypto-mac v0.7.0
  Downloaded 6 crates (284.9 KB) in 1.30s
   Compiling byte-tools v0.3.1
   Compiling subtle v1.0.0
   Compiling fake-simd v0.1.2
   Compiling base64 v0.11.0
   Compiling opaque-debug v0.2.3
   Compiling block-padding v0.1.5
   Compiling generic-array v0.12.4
   Compiling dirs v2.0.2
   Compiling rustls v0.17.0
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling crypto-mac v0.7.0
   Compiling hmac v0.7.1
   Compiling sha-1 v0.8.2
   Compiling webhook-server v0.1.4 (/home/pi/webhook-server)
error[E0308]: mismatched types
  --> src/web.rs:61:37
   |
61 |         server.bind_rustls(address, config)?.run();
   |                                     ^^^^^^ expected struct `rustls::server::ServerConfig`, found struct `ServerConfig`
   |
   = note: perhaps two different versions of crate `rustls` are being used?

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `webhook-server v0.1.4 (/home/pi/webhook-server)`, intermediate artifacts can be found at `/home/pi/webhook-server/target`

Caused by:
  could not compile `webhook-server` due to previous error
```

After a clear-out of my cargo registry and a full re-compile, I see that there are indeed two versions of rustls being compiled:

```
   Compiling rustls v0.18.1
   Compiling rustls v0.17.0
```

I tweaked `Cargo.toml` to use v0.18.1 and it now compiles (and works!) just fine. I guess something else got updated dependencies, and rust/cargo didn't do so well with the diamond dependency. Oh well.

**Comment by Nukesor** [comment]
I really tried to debug this issue, but I cannot get my head around it.
It seems to be some issue with the runtime used by the actix-web runtime and the actix actor usage.

This project seems to be basically not used by anyone as well and I no longer use it myself.

-> I'm thinking about deprecating this crate and yanking the releases

There are other, more mature webhook implementations with a more active developer community.
